// Flat ESLint config for the vet-frontend workspace.
// The `packages/shared/src` block enforces the cross-platform golden rule:
// shared must import cleanly into BOTH a browser (Vite) app and an Expo/RN app,
// so no browser-only or RN-only globals/imports are allowed there.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/.expo/**",
      "**/coverage/**",
      // Generated by `pnpm gen:api` — never hand-edited, never linted.
      "packages/shared/src/types/api.ts",
    ],
  },
  {
    files: ["**/*.{js,mjs,cjs,ts,tsx,mts,cts}"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.node },
    },
  },
  {
    // Mobile config files are CommonJS by Metro/Tailwind/Babel contract — they
    // are loaded via require() by tooling that doesn't understand ESM.
    files: [
      "apps/mobile/metro.config.js",
      "apps/mobile/tailwind.config.js",
      "apps/mobile/babel.config.js",
    ],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  {
    // Mobile is Arabic-first / RTL non-negotiable (PRD §8.1, MOBILE.md). Forbid
    // directional Tailwind utilities (pl-*, pr-*, ml-*, mr-*, border-l/r-*,
    // rounded-l/r-*, text-left/right) in app/ + src/ — use NativeWind logical
    // utilities (ps-/pe-/ms-/me-/border-s/e-/rounded-s/e-/text-start/end).
    files: ["apps/mobile/app/**/*.{ts,tsx}", "apps/mobile/src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "Literal[value=/(?:\\b(?:pl|pr|ml|mr|border-l|border-r|rounded-l|rounded-r)-\\d|\\b(?:text-left|text-right)\\b)/]",
          message:
            "RTL: use the NativeWind logical utility (ps-*, pe-*, ms-*, me-*, border-s-*, border-e-*, rounded-s-*, rounded-e-*, text-start, text-end) — never the directional one.",
        },
        {
          selector:
            "TemplateElement[value.raw=/(?:\\b(?:pl|pr|ml|mr|border-l|border-r|rounded-l|rounded-r)-\\d|\\b(?:text-left|text-right)\\b)/]",
          message:
            "RTL: use the NativeWind logical utility (ps-*, pe-*, etc.) — never the directional one.",
        },
      ],
    },
  },
  {
    // Cross-platform guard: @vet/shared is consumed by web (Vite) and mobile (Expo/RN).
    files: ["packages/shared/src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-globals": [
        "error",
        { name: "window", message: "shared is cross-platform — inject platform behaviour via an adapter interface." },
        { name: "document", message: "shared is cross-platform — no DOM access." },
        { name: "localStorage", message: "shared is cross-platform — use the injected TokenStorage adapter." },
        { name: "sessionStorage", message: "shared is cross-platform — use the injected TokenStorage adapter." },
        { name: "navigator", message: "shared is cross-platform — no browser globals." },
        { name: "location", message: "shared is cross-platform — no browser globals." },
        { name: "history", message: "shared is cross-platform — no browser globals." },
        { name: "alert", message: "shared is cross-platform — no browser globals." },
        { name: "fetch", message: "shared is cross-platform — use the injected Axios client, not the fetch global." },
        { name: "XMLHttpRequest", message: "shared is cross-platform — use the injected Axios client." },
      ],
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "expo",
                "expo-*",
                "react-native",
                "react-native-*",
                "@react-native*",
                "react-dom",
                "react-dom/*",
                "dexie",
                "@powersync/*",
              ],
              message:
                "packages/shared is cross-platform: no platform-specific imports. Inject platform behaviour via an adapter interface, implemented per app.",
            },
          ],
        },
      ],
    },
  },
  eslintConfigPrettier,
);
