// Regenerates src/types/api.ts from the backend OpenAPI spec (NSwag).
// Spec URL: VET_API_SPEC_URL env, else the local dev default.
// Re-run on every backend deploy — this is the spec-drift guard (TECH_STACK § API Contract Strategy).
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const DEFAULT_SPEC_URL = "http://localhost:5180/swagger/v1/swagger.json";
const specUrl = process.env.VET_API_SPEC_URL ?? DEFAULT_SPEC_URL;
const outPath = fileURLToPath(new URL("../src/types/api.ts", import.meta.url));

const BANNER = `/**
 * AUTO-GENERATED by \`pnpm gen:api\` (openapi-typescript) from the backend OpenAPI spec.
 * DO NOT EDIT BY HAND. Re-run after every backend deploy (spec-drift guard).
 * Source: ${specUrl}
 */
`;

try {
  console.log(`gen:api → reading spec from ${specUrl}`);
  const ast = await openapiTS(new URL(specUrl));
  writeFileSync(outPath, BANNER + astToString(ast));
  console.log(`gen:api → wrote ${outPath}`);
} catch (err) {
  console.error("gen:api failed. Is the backend running and serving the spec?");
  console.error(`  Tried: ${specUrl}  (override with VET_API_SPEC_URL)`);
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
}
